camunda.bpm.admin-user:
  id: sa
  password: root
spring:
  datasource:
    username: camunda
    url: jdbc:postgresql://localhost:5432/camunda-engine-db
    password: root
    driver-class-name: org.postgresql.Driver

