engines:
  'camunda':
    name: camunda
    defaultTenant:
      id: null
      name: null
    rest: 'http://localhost:8080/engine-rest'
    importEnabled: true
    eventImportEnabled: false
    authentication:
      enabled: true
      password: 'demo'
      user: 'demo'
    webapps:
      endpoint: 'http://localhost:8080/camunda'
      enabled: true