version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: root
      POSTGRES_DB: camunda-engine-db
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
