services:
  database:
    container_name: database
    image: 'postgres:12.11'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PASSWORD_ENCRYPTION: ${PASSWORD_ENCRYPTION}
    volumes:
      - ./docker_data/postgres/data/:/var/lib/postgresql/data/
    networks:
          - camunda-platform
  camunda:
    container_name: camunda
    hostname: camunda
    image: 'registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee@sha256:e45797ef8dd51db2574afd188da07564bbe34d4096b02ecc1ddeecc6f563e93a'
    ports:
      - "8080:8080"
    links:
      - "database:database"
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - camunda-platform
    depends_on:
      - database
      - elasticsearch
  optimize:
    container_name: optimize
    image: 'registry.camunda.cloud/optimize-ee/optimize@sha256:6dd5b8a9ddc1962b77335e2e131e03fd6c3ca3ff7d1b32b51d023b69da3a0cde'
    ports:
      - "8083:8090"
    environment:
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=${ELASTICSEARCH_HTTP_PORT}
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
      - OPTIMIZE_CAMUNDABPM_REST_URL=${OPTIMIZE_CAMUNDABPM_REST_URL}
      - CAMUNDA_BPMN_URL=${CAMUNDA_BPMN_URL}
      - OPTIMIZE_ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - JAVA_SYSTEM_PROPERTIES=-Xmx1024m
    networks:
      - camunda-platform
    depends_on:
      - camunda
      - database
      - elasticsearch
    volumes:
      - ./optimize-config/environment-config.yaml:/optimize/config/environment-config.yaml
      - ./optimize-config/optimizeLicense.txt:/optimize/config/optimizeLicense.txt
    links:
      - "camunda:camunda"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - camunda-platform

networks:
  camunda-platform: