version: '3'
services:
  databace:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DS_USR_CE}
      POSTGRES_PASSWORD: ${DS_PASS_CE}
      POSTGRES_DB: ${DS_NAME_CE}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  camunda:
    container_name: camunda-engine
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: camunda-engine:latest
    ports:
      - '8080:8080'
    environment:
      - DS_URL_CE=${DS_PROVIDER_CE}:${DS_PORT_CE}/${DS_NAME_CE}
      - DS_PASS_CE=${DS_PASS_CE}
      - DS_USR_CE=${DS_USR_CE}
      - USR_CE=${USR_CE}
      - PASS_CE=${PASS_CE}
      - BOOK_API_URL=${BOOK_API_URL}
    depends_on:
      - databace
    links:
      - databace
