services:
  optimize:
    container_name: optimize
    image: '${OPTIMIZE_REPOSITORY:-registry.camunda.cloud/optimize-ee/optimize}${OPTIMIZE_SHA_IMAGE:-@sha256:6dd5b8a9ddc1962b77335e2e131e03fd6c3ca3ff7d1b32b51d023b69da3a0cde}'
    ports:
      - ${OPTIMIZE_WEBAPPS_CONTAINER_HTTP_PORT}:${OPTIMIZE_WEBAPPS_CONTAINER_HTTP_PORT}
      - ${OPTIMIZE_WEBAPPS_CONTAINER_HTTPS_PORT}:${OPTIMIZE_WEBAPPS_CONTAINER_HTTPS_PORT}
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=${OPTIMIZE_CAMUNDABPM_HOST_PREFIX}://${OPTIMIZE_CAMUNDABPM_HOST}:${OPTIMIZE_CAMUNDABPM_PORT}/${OPTIMIZE_CAMUNDABPM_REST:-engine-rest}
      - OPTIMIZE_CAMUNDABPM_WEBAPPS_URL=${OPTIMIZE_CAMUNDABPM_HOST_PREFIX}://${OPTIMIZE_CAMUNDABPM_HOST}:${OPTIMIZE_CAMUNDABPM_PORT}/${OPTIMIZE_CAMUNDABPM_WEBAPP:-camunda}
      - OPTIMIZE_CAMUNDABPM_EVENT_IMPORT_ENABLED=${OPTIMIZE_CAMUNDABPM_EVENT_IMPORT_ENABLED}
      - OPTIMIZE_ELASTICSEARCH_HOST=${OPENSEARCH_HOST}
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=${OPENSEARCH_HTTP_PORT}
      - OPTIMIZE_ELASTICSEARCH_HTTPS_PORT=${OPENSEARCH_HTTP_PORT}
      - JAVA_OPTS=${JAVA_OPTS}
      - JAVA_SYSTEM_PROPERTIES=${JAVA_SYSTEM_PROPERTIES}
      - OPTIMIZE_AUTHENTICATION_ENABLED=${OPTIMIZE_AUTHENTICATION_ENABLED}
      - ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE=${ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE}
    networks:
      - optimize-network
    depends_on:
      - opensearch
    volumes:
      - ${ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE}:/optimize/config/environment-config.yaml
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-latest}
    environment:
      - node.name=opensearch
      - cluster.name=opensearch-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/opensearch/data
    networks:
      optimize-network:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION:-latest}
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - optimize-network

volumes:
  data01:
networks:
  optimize-network: