services:
  optimize:
    container_name: optimize
    image: '${OPTIMIZE_REPOSITORY}${OPTIMIZE_SHA_IMAGE}'
    ports:
      - ${OPTIMIZE_WEBAPPS_CONTAINER_HTTP_PORT}:${OPTIMIZE_WEBAPPS_CONTAINER_HTTP_PORT}
      - ${OPTIMIZE_WEBAPPS_CONTAINER_HTTPS_PORT}:${OPTIMIZE_WEBAPPS_CONTAINER_HTTPS_PORT}
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=${OPTIMIZE_CAMUNDABPM_HOST_PREFIX}://${OPTIMIZE_CAMUNDABPM_HOST}:${OPTIMIZE_CAMUNDABPM_PORT}/${OPTIMIZE_CAMUNDABPM_REST}
      - OPTIMIZE_CAMUNDABPM_WEBAPPS_URL=${OPTIMIZE_CAMUNDABPM_HOST_PREFIX}://${OPTIMIZE_CAMUNDABPM_HOST}:${OPTIMIZE_CAMUNDABPM_PORT}/${OPTIMIZE_CAMUNDABPM_WEBAPP}
      - OPTIMIZE_CAMUNDABPM_EVENT_IMPORT_ENABLED=${OPTIMIZE_CAMUNDABPM_EVENT_IMPORT_ENABLED}
      - OPTIMIZE_ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=${ELASTICSEARCH_HTTP_PORT}
      - OPTIMIZE_ELASTICSEARCH_HTTPS_PORT=${ELASTICSEARCH_HTTPS_PORT}
      - JAVA_OPTS=${JAVA_OPTS}
      - JAVA_SYSTEM_PROPERTIES=${JAVA_SYSTEM_PROPERTIES}
      - OPTIMIZE_AUTHENTICATION_ENABLED=${OPTIMIZE_AUTHENTICATION_ENABLED}
      - ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE=${ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE}
    networks:
      - optimize-network
    depends_on:
      - elasticsearch
    volumes:
      - ${ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE}:/optimize/config/environment-config.yaml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - ${ELASTICSEARCH_HTTP_PORT}:${ELASTICSEARCH_HTTP_PORT}
      - ${ELASTICSEARCH_HTTPS_PORT}:${ELASTICSEARCH_HTTPS_PORT}
    networks:
      - optimize-network

networks:
  optimize-network: