services:
  optimize:
    container_name: optimize
    image: 'registry.camunda.cloud/optimize-ee/optimize@sha256:6dd5b8a9ddc1962b77335e2e131e03fd6c3ca3ff7d1b32b51d023b69da3a0cde'
    ports:
      - "8083:8090"
    environment:
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=${ELASTICSEARCH_HTTP_PORT}
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
      - OPTIMIZE_CAMUNDABPM_REST_URL=${OPTIMIZE_CAMUNDABPM_REST_URL}
      - CAMUNDA_BPMN_URL=${CAMUNDA_BPMN_URL}
      - OPTIMIZE_ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - JAVA_SYSTEM_PROPERTIES=-Xmx1024m
    networks:
      - optimize-platform
    depends_on:
      - elasticsearch
    volumes:
      - ./optimize-config/environment-config.yaml:/optimize/config/environment-config.yaml
      - ./optimize-config/optimizeLicense.txt:/optimize/config/optimizeLicense.txt
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - optimize-platform

networks:
  optimize-platform: