{
 "title": "Job Executor",
 "tags": [
  "OK",
  "Camunda"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Camunda - JobExecutor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ActiveThreads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      { "expr": "executor_active_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PoolSizeThreads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      { "expr": "executor_pool_size_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PoolCoreThreads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      { "expr": "executor_pool_core_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PoolMaxThreads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      { "expr": "executor_pool_max_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CompletedTasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "executor_completed_tasks_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "QueuedTasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      { "expr": "executor_queued_tasks", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "QueuedRemainingTasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "executor_queue_remaining_tasks", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}